### ISSUE TITLE
build a docker image for metacat

### ISSUE THREAD

**Issue by mbjones** [NCEAS/metacat#1218]
Create a configuration that allows Metacat to start up as a docker image with a simple command.  An example deployment would include three containers:

- [ ] a *tomcat*-based container with Metacat and MetacatUI installed
- [ ] a *postgres* container to run the metacat database
- [ ] an apache *httpd* container configured with SSL as a proxy using Let's Encrypt

Of course, the metacat image itself could be used in other deployment contexts by providing environment variables that configure it to connect to the remote database.

**Comment by mbjones** [comment]
Be sure to check thread in #1226 for some excellent suggestions.

**Comment by mbjones** [comment]
Consider whether to add a Kubernetes deployment descriptor as well to make it easy to deploy there.

**Comment by mbjones** [comment]
Initial start on this functionality is in the `feature-docker` branch (https://github.com/NCEAS/metacat/tree/feature-docker), but that needs to be merged with the many release changes that have happened recently.

**Comment by artntek** [comment]
I've decide k8s and helm work are getting off-topic for **build a docker image for metacat #1218**, so I'll leave this issue to describe the docker work ONLY, and have created a new issue for the k8s & helm work: #1623 - **Metacat is deployable on Kubernetes, using a Helm Chart**

**Comment by artntek** [comment]
### TODO items on the Docker work

* create a GitHub action for building docker images and storing them in GHCR
* Alternative method of applying schema upgrades in Docker? Or apply via helm hooks? (see [flyway](https://flywaydb.org/))
* Make metacatui install optional (and maybe do separately with helm?)

**Comment by artntek** [comment]
Closing this. Remaining TODO items are already represented in #1623 and related issues
