### ISSUE TITLE
Update Apache setup docs to match current practice

### ISSUE THREAD

**Issue by amoeba** [NCEAS/metacat#1447]
Rani recently ran into an issue getting an HTTP 413 (Request entity too large) when triggering `MNStorage.create` via R. I went to advise and noticed a mismatch with how I thought we were doing things, how the Metacat documentation says we do things, and how we are actually doing things. I brought this up on our July 2nd developer call and we decided to revisit this.

**Background**

This is something we've seen for years and has to do with our use of client certificates for CN<->MN communication and interacts with `Location` and/or `Directory` directives in our configs and how Apache handles TLS. See the [Apache Bugzilla link](https://bz.apache.org/bugzilla/show_bug.cgi?id=39243) for more.

Way back, we wanted to set `SSLVerifyClient optional` to allow the CN to connect with a client certificate but allow other clients such as web browsers to connect without one. Safari doesn't behave like other browsers and behaves poorly so we put in a config block like this:

```xml
...snip...
SSLVerifyClient none
...snip...
<Location "/metacat/d1/mn">
  <If " ! ( %{HTTP_USER_AGENT} =~ /(windows|chrome|mozilla|safari|webkit)/i )">
    SSLVerifyClient optional
  </If>
</Location>
...snip...
```

This worked great, until `libcurl` deprecated sending the HTTP `Expect` header on POST requests due to it not being uniformly handled across web servers. The R `curl` package followed suit and made it impossible to send this header which made it impossible for anyone depending on the R `curl` package to send large POST bodies. They'd get an HTTP 413 (Request entity too large) when their POST request had a body over some size. To solve this, we extended the `If` block above to add more user agents:

```xml
...snip...
SSLVerifyClient none
...snip...
<Location "/metacat/d1/mn">
  <If " ! ( %{HTTP_USER_AGENT} =~ /(windows|chrome|mozilla|safari|webkit|httr|julia|python)/i )">
    SSLVerifyClient optional
  </If>
</Location>
...snip...
```

And all was well. Until we upgraded some MNs to Ubutnu 18.04 and got Apache 2.4.29 and started seeing [significant delays](https://redmine.dataone.org/issues/8823) in requests due to TLS renegotiation.

These `If` blocks were removed from hosts like the ADC and KNB and... everything was fine. The KNB currently has `SSLVerifyClient optional` and I can do an `MNStorage.create` call with a 50MiB file. At this point it's not clear whether this is a change that occurred in Apache or in the R ecosystem. R is not sending an `Expect` header so it seems Apache may be doing something differently now.

This is a good time to figure out where we're at on the above and also generally harmonize our stock Apache configs and documentation.

**Tasks**

- [ ] Take a look at the stock Tier 1 MN config at `src/scripts/debian/metcat-site.conf` and edit as needed
- [ ] Merge `metacat-site.conf` and `metacat-site-ssl.conf` into a single config as per previous discussions to simplify things
- [ ] Update our Tier 1 and Tier 2 config examples to match how we do things now WRT not only `SSLVerifyClient` but also other things we need enabled like CORS, FallbackResource, replication, etc
- [ ] Resolve https://github.com/NCEAS/metacat/issues/1251

Ideally, what's done here should help address the issue that started this by updating our documentation such that Rani could be pointed to that documentation and go from there.

**Comment by amoeba** [comment]
Hey @csjx, @taojing2002, I ran into question while working on this:

Do we even need directives like

  ```xml
  <Directory "/var/www/webapps/metacat/cgi-bin/"> 
    AllowOverride None 
    Options ExecCGI 
    Require all granted
  </Directory> 
  ```
(and anything CGI script related) now that LDAP login and the Perl registry are a thing of the past? It seems we can simplify our base config.

I use a config like this for my dev vm (Tier 1):

```xml
<VirtualHost *:80>
	ServerName neutral-cat.nceas.ucsb.edu
	Redirect permanent / https://neutral-cat.nceas.ucsb.edu
</VirtualHost>
<IfModule mod_ssl.c>
	<VirtualHost *:443>
		ServerName netural-cat.nceas.ucsb.edu
		ServerAdmin mecum@nceas.ucsb.edu

		ErrorLog ${APACHE_LOG_DIR}/error.log
		CustomLog ${APACHE_LOG_DIR}/access.log combined

		DocumentRoot /var/www/neutral-cat.nceas.ucsb.edu

		FallbackResource /index.html

		# Fully support DataONE PIDs in URLs (e.g., http://hello is a
		# valid PID)
		AllowEncodedSlashes On
		AcceptPathInfo      On

		# XHR / CORS Support
		Header always append X-Frame-Options SAMEORIGIN
		SetEnvIf Origin "^(.*)$" ORIGIN_DOMAIN=$1
		Header set Access-Control-Allow-Origin "%{ORIGIN_DOMAIN}e" env=ORIGIN_DOMAIN
		Header set Access-Control-Allow-Headers "Authorization, Content-Type, Origin, Cache-Control"
		Header set Access-Control-Allow-Methods "GET, POST, PUT, OPTIONS"
		Header set Access-Control-Allow-Credentials "true"

		# Sitemap support
		RewriteEngine On
		RewriteRule ^/(sitemap.+) /metacat/sitemaps/$1 [R=303]

		# Reverse proxy Metacat
		ProxyPass /metacat ajp://localhost:8009/metacat	nocanon

		SSLCertificateFile /etc/letsencrypt/live/neutral-cat.nceas.ucsb.edu/fullchain.pem
		SSLCertificateKeyFile /etc/letsencrypt/live/neutral-cat.nceas.ucsb.edu/privkey.pem
		Include /etc/letsencrypt/options-ssl-apache.conf
	</VirtualHost>
</IfModule>
```

and all seems to work fine. I'd like to take this as a chance to clean things up if we can.

**Comment by amoeba** [comment]
Okay, `dataone.rst` updated in https://github.com/NCEAS/metacat/commit/c3b54601e9e5f041f86044189090d12425eb9946. Would either if you like to take a look? I'll message Rani with this in Slack now.

**Comment by amoeba** [comment]
Just a note for myself for later. I noticed that we don't include a `FallbackResource` directive in our example config which people need to use now. Should update the docs.
