### ISSUE TITLE
Move arcticdata.io (Production) to Kubernetes

### ISSUE THREAD

**Issue by artntek** [NCEAS/metacat#1954]
Similar to #1932; 

## checklist:

- [x] Work with @nickatnceas to copy production data for testing: 
    - [x] Time how long it takes to...
        - [x] Copy the production postgres data (`arcticdata.io:/var/lib/postgresql`) to the PROD ceph volume at `/mnt/ceph/repos/arctic/postgresql` (treat it like a hot backup).
            - NOTE: we do not need the `/var/lib/postgresql/10` directory
        - [x] copy the following subset of production data from `arcticdata.io:/var/metacat` to the PROD ceph volume at `/mnt/ceph/repos/arctic/metacat`:

            ```shell
            # /var/metacat/...
            16K	    ./certs
            63T	    ./data
            8.0K        ./dataone
            3.9G        ./documents
            0           ./inline-data
            500K        ./logs
            ``` 
            - Actual Times taken for /var/metacat/data:
              - initial rsync
                ```shell
                root@arctica:/var/metacat# time rsync -aHAX --delete /var/metacat/data/ /mnt/pdg/repos/arctic/metacat/data/
                
                real    14286m43.628s
                user    1131m15.740s
                sys     3907m38.871s
                ## -> 9.92 days
                ```
              - subsequent repeat rsync
                ```shell
                brooke@arctica:~$ time sudo rsync -rltDHX  /var/metacat/data/ /mnt/pdg/repos/arctic/metacat/data/
                [sudo] password for brooke:
                
                real	4m19.047s
                user	0m15.747s
                sys	0m34.912s
                ```
              
### Persistent Volumes
- [x] Set up a PV to point to PROD cephfs `.../repos/arctic/metacat` for metacat
- [x] Set up a PV to point to PROD cephfs `.../repos/arctic/postgres` for postgres
- [x] Create a PVC for Postgresql; see `prod_cluster/metacatarctic/pvc--metacatarctic-postgres.yaml`
- [x] "csi-cephfs-sc-ephemeral" storageClass missing. Ask @nickatnceas to add, like he did for dev cluster:
```shell
  storageclass.storage.k8s.io "csi-cephfs-sc-ephemeral" not found
```

### MetacatUI setup
- [x] Copy config (tokens) from adc server

### Metacat Config
- [x] Add `values.yaml` overrides for non-default 2.19 settings (diff arcticdata.io `$TOMCAT_HOME/webapps/metacat/WEB-INF/metacat.properties` with default `metacat.properties` from 2.19 release)
- [x] Add `values.yaml` overrides for newly-introduced 3.0 settings (diff default `metacat.properties` from 3.0.0 release with default `metacat.properties` from 2.19 release)
- [x] Compare with test.arcticdata.io values overrides as a sanity check

### First Deployment 
- [x] Complete steps in ["First Install - IMPORTANT IF MOVING DATA FROM AN EXISTING LEGACY DEPLOYMENT"](https://github.nceas.ucsb.edu/NCEAS/k8s-cluster-config/blob/main/MetacatQuickRef.md) BEFORE first startup!

- [x] solr pods not starting. root cause from logs:
  ```shell
  $ kc logs pod/metacatarctic-solr-1
    /scripts/setup.sh: line 8: /opt/bitnami/scripts/solr/entrypoint.sh: Permission denied
  ```
  **SOLVED** - was overriding `extraVolumes` values, and the override didn't include the permissions line

- [x] `https://arctic-prod.test.dataone.org/catalog/` (trailing slash) works, but `https://arctic-prod.test.dataone.org/catalog` gives a 404 (nginx)
    - See https://github.com/kubernetes/ingress-nginx/issues/646
    - See https://stackoverflow.com/questions/71424259/why-url-re-writing-is-not-working-when-i-do-not-use-slash-at-the-end
      ```
        - path: /link1(/|$)
      ```
- [x] ensure all data and documents files are group writeable (otherwise, hashstore upgrader can't create hard links):
    ```shell
    sudo find /mnt/ceph/repos/arctic/metacat/data/ -type f ! -perm -g=w -exec chmod g+w {} +
    ```
- [x] `chown -R 59997:59997` the ceph dir corresponding to `/var/metacat`, and update values.yaml to use this uid:gid
    ```shell
    brooke@datateam:/mnt/ceph/repos/arctic$ time sudo chown -R 59997:59997 metacat

    real	4m7.026s
    user	0m0.004s
    sys	0m0.027s
    ```
- [x] Hostname aliases and rewrite rules
    - Figure out how to do these with ingress; see [all-sites-enabled.conf](https://github.nceas.ucsb.edu/NCEAS/k8s-cluster-config/blob/4bb7dc02274e44270889c328edf147c65fa27443/prod_cluster/metacatarctic/reference/all-sites-enabled.conf#L1). Lots of complexity - eg http://aoncadis.org aliased to adc.io, and site conf has RewriteMaps each having >3700 entries.
    - EXPLANATION: aoncadis.org was the predecessor to the ADC site. These rewrite rules map existing, old dataset urls to their new locations on ADC - so these rewrites need to be maintained somewhere
    - [x] Leave all the redirects/other sites on the current Apache host, and move only [arcticdata.io](http://arcticdata.io/).

### ATTENTION: Still To Do Before Final Deployment
- [x] Time hashstore conversion
- [x] Time reindex-all
- [x] MetacatUI + WordPress setup. How do we host it and link to k8s metacat?
    - [x] ACTION: use a wordpress image/bitnami chart, deployed separately from the metacat helm chart

- [x] ACTION: Ask @nickatnceas for help with letsencrypt certs - do we need to remove `arcticdata.io` from wildcard cert on arctica? NOTE: we still need subdomain certs there (ie status.adc, beta.adc).

- [x] Skip 3.0.0 and deploy 3.1.0, but only after it's been running on less-trafficked hosts for a while. See proposed release plan in Issue #1984.

**Comment by artntek** [comment]
update from Nick on rsync of /var/metacat/data:
> _after 16 hours we have 3.3 T copied… so looking like ~12 days until it’s finished_

**Comment by artntek** [comment]
Trying to resolve "permission denied" error on solr startup.
```shell
/scripts/setup.sh: line 8: /opt/bitnami/scripts/solr/entrypoint.sh: Permission denied
```

Can't test from within the solr pods, because they never start up - so instead created a (busybox) pod to do the same configmap mounts:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: metacatarctic-solr-config-mount-test
  namespace: arctic
spec:
  containers:
    - image: docker.io/busybox
      imagePullPolicy: IfNotPresent
      name: solr-config-mount
      command: [ "/bin/sh" ]
      args: [ "-c", "while true; do sleep 86400; done" ]
      volumeMounts:
        - name: scripts
          mountPath: /scripts/setup.sh
          subPath: setup.sh
        - mountPath: /solrconfig
          name: solr-config
        - mountPath: /opt/bitnami/scripts/solr/entrypoint.sh
          name: solr-config
          subPath: entrypoint.sh
  volumes:
    - name: scripts
      configMap:
        name: metacatarctic-solr-scripts
        defaultMode: 0755
    - configMap:
        name: metacatarctic-indexer-configfiles
        defaultMode: 0755
      name: solr-config
```

...and this shows that the entrypoint script is indeed non-executable:
```shell
$ ls -la /opt/bitnami/scripts/solr/entrypoint.sh
-rw-r--r--    1 root     root           780 Oct 14 22:37 /opt/bitnami/scripts/solr/entrypoint.sh
```

BUT - if I look at one of the solr pods on the existing test.adc.io instance, it's different:

```shell
 $ kcexec -it metacatarctic-solr-0 -- bash -c "ls -la /opt/bitnami/scripts/solr/entrypoint.sh"
-rwxrwxrwx 1 root 1001 780 Jul 29 19:44 /opt/bitnami/scripts/solr/entrypoint.sh
```

Using the same chart, why the difference between dev and prod clusters??

**Comment by mbjones** [comment]
For the Testing section, here's a quick rundown:

### Get the R package `dataone` installed

- Download and install R (required) and RStudio (nice but optional)
- Checkout [`rdataone`](https://github.com/DataONEorg/rdataone) and (probably) switch to the `develop` branch, depending on what you need to test
- open `rdataone/dataone.RProj` in RStudio
- run `install.packages(c('remotes', 'devtools'))`
- run `devtools::load_all()` to load the current `dataone` library code for testing
- run `remotes::install_deps()` to install all of the package dependencies

### Run the tests against standard nodes

- login to `https://dev.nceas.ucsb.edu` and copy your token for R from the web UI; paste the token `options` command into the R console and run it
- run `devtools::test()` to run the original tests against standard nodes

### To run tests against a different node

- Modify the nodes to be tested in the test framework file: https://github.com/DataONEorg/rdataone/blob/develop/tests/testthat/helper-base.R 
    - For example, change [line 21](https://github.com/DataONEorg/rdataone/blob/develop/tests/testthat/helper-base.R#L21) `d1cTestKNB <- D1Client("STAGING", "urn:node:mnTestKNB")` to use a different node for CRUD tests
- ensure you are logged in as described above
- run `devtools::test()` as described above

**Comment by artntek** [comment]
## hashstore conversion notes

* Started running the conversion on the ceph copy of the prod ADC corpus: 11/11/24 at ~4pm.
* Started with:
  * a completely empty /var/metacat/hashstore/ directory
  * empty `checksums` DB table
  * `systemmetadata.checksum_algorithm` fixed to contain only "official" names, thus avoiding `noSuchAlgorithm` errors, and
  * ownership & permissions fixed so converter can access the data files on disk

* https://arcticdata.io/metacat/d1/mn/v2/object shows `total="1115730"`, and converter creates 5 checksums per object, so `checksums` table should ultimately contain of the order of 5.5M rows, not accounting for errors.
  ```shell
  kubectl exec metacatarctic-postgresql-0 -- \
      bash -c "psql -U metacat -c 'select count(*) from checksums'"
  ```

Errors encountered and explained:
* TBC

**Comment by artntek** [comment]
11/19/24: Second conversion (comprising only the failed objects from last time) took 42 minutes
(Douglas Adams would approve)

see https://github.com/NCEAS/metacat/issues/1964#issuecomment-2484552430

**Comment by artntek** [comment]
### 11/19/24: Did another rsync

**Comment by artntek** [comment]
## Initial index-all
```
[25/Nov/2024:21:47:20 +0000] PUT /metacat/d1/mn/v2/index?all=true
```

**Comment by artntek** [comment]
## indexer log errors to Investigate

134205 total errors across all 50 index workers.

* 9999 occurrences: 
```
java.lang.IllegalArgumentException: The southLatitude must not be greater than the northLatitude
	at org.dataone.cn.indexer.convert.GeohashConverter.convert(GeohashConverter.java:90)
	at org.dataone.cn.indexer.parser.CommonRootSolrField.getFields(CommonRootSolrField.java:70)
	at org.dataone.cn.indexer.parser.BaseXPathDocumentSubprocessor.processDocument(BaseXPathDocumentSubprocessor.java:124)
	at org.dataone.cn.indexer.parser.ScienceMetadataDocumentSubprocessor.processDocument(ScienceMetadataDocumentSubprocessor.java:42)
	at org.dataone.cn.indexer.SolrIndex.process(SolrIndex.java:238)
	at org.dataone.cn.indexer.SolrIndex.insert(SolrIndex.java:382)
	at org.dataone.cn.indexer.SolrIndex.update(SolrIndex.java:455)
	at org.dataone.cn.indexer.IndexWorker.indexObject(IndexWorker.java:440)
	at org.dataone.cn.indexer.IndexWorker$1$1.run(IndexWorker.java:357)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
```

* 13386 occurrences:
```
<lst name="error">
  <lst name="metadata">
    <str name="error-class">org.apache.solr.common.SolrException</str>
    <str name="root-error-class">org.apache.solr.common.SolrException</str>
  </lst>
  <str name="msg">version conflict for arctic-data.9404.1 expected=1816806643690635264 actual=1816892898388475904</str>
  <int name="code">409</int>
</lst>
</response>
 [org.dataone.cn.indexer.solrhttp.HTTPService:sendUpdate:147]
```

* 2992 occurrences:
```
dataone-indexer 20241127-18:45:14: [ERROR]: Cannot index the task
for identifier resource_map_urn:uuid:3209759f-4985-4cf3-aa4d-55b3c83a5ad2
since Solr index doesn't have the information about the id
resource_map_urn:uuid:f3e9ed0d-762d-43e9-b7fd-cdb07e753520 which is a component
in the resource map resource_map_urn:uuid:3209759f-4985-4cf3-aa4d-55b3c83a5ad2.
Metacat-Index can't process the resource map prior to its
components. [org.dataone.cn.indexer.IndexWorker:indexObject:464]
```

**Comment by artntek** [comment]
Closing and moving testing to #2088
